#
# weechat -- alias.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use commands like /set or /fset to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/weechat/quickstart/
#

config_version = 2

[cmd]
ada = "/msg chanserv akick #linuxmint-help del $1; /msg chanserv akick #linuxmint-chat del $1"
aka = "/msg chanserv akick #linuxmint-help add $1 !T $2-; /msg chanserv akick #linuxmint-chat add $1 !T $2-"
ala = "/msg chanserv akick #linuxmint-help list; /msg chanserv akick #linuxmint-chat list"
ame = "allchan /me $1-"
amsg = "allchan /say $1-"
banlist = "/quote MODE $channel +b"
c = "/buffer clear"
dmsg = "/msg =$1 $2-"
grep = "/lastlog -r -- $1-"
ignall = "/ignore $1!*@* ALL"
kill = "/quote KILL $1 :$2-"
mute = "/mode #linuxmint-help +b m:$1; /mode #linuxmint-chat +b m:$1"
omsg = "/msg @$channel $1-"
onotice = "/notice @$channel $1-"
opoff = "/msg ChanServ deop #linuxmint-chat; /msg ChanServ deop #linuxmint-help"
opoffmint = "/msg ChanServ deop #mintops"
opon = "/msg ChanServ op #linuxmint-chat; /msg ChanServ op #linuxmint-help"
oponmint = "/msg ChanServ op #mintops"
raw = "/quote $1-"
servhelp = "/quote HELP"
sping = "/ping"
squery = "/quote SQUERY $1 :$2-"
sslserver = "/server -ssl $1"
sv = "/echo HexChat $weechat.version $weechat.name"
uptime = "/quote STATS u"
ver = "/ctcp $1 VERSION"
version = "/ctcp $1 VERSION"
wallops = "/quote WALLOPS :$1-"
wi = "/quote WHOIS $1"
wii = "/quote WHOIS $1 $1"

[completion]
