"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](fg:neon_green)\
$username\
[ >](bg:bg_dark fg:neon_green)\
$directory\
[](bg:bg_dark fg:neon_green)\
$git_branch\
$git_status\
$line_break\
$character"""

palette = "mycolors"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:bg_dark fg:white"
style_root = "bg:red fg:white"
format = '[$user]($style)'

[directory]
style = "bg:bg_dark fg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:blue_dim fg:white"
format = '[[ $symbol $branch ](fg:white bg:green)]($style)'

[git_status]
style = "bg:bg_dark"
format = '[[($all_status$ahead_behind )](fg:yellow bg:bg_dark)]($style)'

[line_break]
disabled = true


[palettes.mycolors]
bg_dark         = "#333333"
grey            = "#4c4f69"
green           = "#40a02b"
neon_green      = "#12BB02"
blue_dark       = "#1144AB"
blue_darker     = "#1C3A5E"
blue_light      = "#8DFBD2"
teal            = "#179299"
sky             = "#04a5e5"
sapphire        = "#209fb5"
off_white       = "#E4E4E4"
white           = "#FFFFFF"
red             = "#d20f39"
orange          = "#fe640b"
orange_yellow   = "#df8e1d"
yellow          = "#FFEA00"
