[general]
live_config_reload = true

[window]
opacity = 0.87
blur = true

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "dark" # "light"

[font]
size = 16.0

[selection]
save_to_clipboard = true

#[[keyboard.bindings]]
#key = "Down"
#mods = "Control|Shift"
#chars = "\u001b[1;6B"
